### PR TITLE
fix: kosmosctl using issues

### LINKED ISSUE #57: kosmosctl using issues
**What happened**:
When using the kosmosctl tool to operate kosmos for cluster join/unjoin, the following problems exist: the image is missing, and the cluster configuration parameters are abnormal and cannot be loaded.
2728e6f897d49a4a439c460ad5f1469
image
image
After the kosmos service was started in the member cluster, some service electors did not start as expected，like：
image

**What you expected to happen**:
image was successfully pulled and the service started normally.

**How to reproduce it (as minimally and precisely as possible)**:
step 1: kosmosctl join -f cluster.yaml --master-kubconfig m-kubconfig --cluster-kubconfig c-kubconfig
step 2: kubectl logs -f clusterlink-operator-xxx -n clusterlink-system
step 3: kubectl get pod -n clusterlink-system

**Anything else we need to know?**:

**Environment**:
- Kosmos version:
- Others:

### PR DESCRIPTION
**Pull request by rxy0210**
fix: kosmosctl using issues
it fix problems (the image is missing, and the cluster configuration parameters are abnormal and cannot be loaded)
Fixes #57 
@ONE7live

### CODE REVIEW

File: pkg/kosmosctl/unjoin/unjoin.go [hunk 1]
```diff
@@ -108,33 +108,23 @@ func (o *CommandUnJoinOptions) Validate() error {
...
 	for {
-		// Wait 3 second
-		time.Sleep(3 * time.Second)
-		_, err := o.DynamicClient.Resource(schema.GroupVersionResource{
+		err := o.DynamicClient.Resource(schema.GroupVersionResource{
 			Group:    "kosmos.io",
 			Version:  "v1alpha1",
 			Resource: "clusters",
-		}).Namespace("").Get(context.TODO(), args[0], metav1.GetOptions{})
+		}).Namespace("").Delete(context.TODO(), args[0], metav1.DeleteOptions{})
```
Comment (ONE7live) [inline pkg/kosmosctl/unjoin/unjoin.go:116]: here logic seems be changed, and the part that originally checked if the cluster was deleted has been removed, why?

Comment (rxy0210) [reply pkg/kosmosctl/unjoin/unjoin.go:116]: Simplified code, delete instead of get
now logic: first delete -> wait -> next delete 
if delete success firstly, 'next delete' will return not found error. we will break.
